In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50])

print("Array:", a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimensions:", a.ndim)
print("Data Type:", a.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Dimensions: 1
Data Type: int64


In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix:\n", a)
print("Transpose:\n", a.T)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [5]:
a = np.array([10, 20, 30, 40, 50])

print("Maximum:", np.max(a))
print("Minimum:", np.min(a))
print("Mean:", np.mean(a))
print("Sum:", np.sum(a))

Maximum: 50
Minimum: 10
Mean: 30.0
Sum: 150


In [6]:
a = np.arange(1, 13)

b = a.reshape(3, 4)

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
a = np.arange(50, 101, 5)

print(a)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [8]:
a = np.array([-5, 10, -3, 20, -8])

a[a < 0] = 0

print(a)

[ 0 10  0 20  0]


In [9]:
a = np.array([10, 20, 30, 40, 50])

mean = np.mean(a)

print("Mean:", mean)
print("Elements:", a[a > mean])

Mean: 30.0
Elements: [40 50]


In [10]:
a = np.eye(5, dtype=int)

print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a.flatten())

[1 2 3 4 5 6 7 8 9]


In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Row Sum:", np.sum(a, axis=1))
print("Column Sum:", np.sum(a, axis=0))

Row Sum: [ 6 15 24]
Column Sum: [12 15 18]


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Dot Product:", np.dot(a, b))

Dot Product: 32


In [14]:
a = np.array([10, 20, 30, 40, 50])

print("Reversed Array:", a[::-1])

Reversed Array: [50 40 30 20 10]


In [15]:
a = np.array([10, 50, 20, 5, 30])

print("Maximum Index:", np.argmax(a))
print("Minimum Index:", np.argmin(a))

Maximum Index: 1
Minimum Index: 3


In [16]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print("Horizontal:\n", np.hstack((a, b)))
print("Vertical:\n", np.vstack((a, b)))

Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
